# ===============================
# Configuracion general
# ===============================
# Nombre de la aplicacion
spring.application.name                    = VetManadaWoof
# Puerto en el que corre la app
#server.port                                = 8088
# Ruta base ("/" significa raiz)
server.servlet.context-path                = /

app.jwt.secret                             = mySuperSecretKeyForJWTGenerationInVetManadaWoofApplication2024

app.jwt.expiration-ms                      = 86400000

# ===============================
# Configuracion de la base de datos
# ===============================
# URL de conexion a MySQL
#spring.datasource.url                      = jdbc:mysql://localhost:3306/vet_manada_woof
# Usuario de la BD
#spring.datasource.username                 =root
# Contrasena de la BD
#spring.datasource.password                 =ben10000
# Driver de MySQL
#spring.datasource.driver-class-name        = com.mysql.cj.jdbc.Driver


# ===============================
# Configuracion de JPA / Hibernate
# ===============================
# Valida esquema segun entidades (solo en dev)
#spring.jpa.hibernate.ddl-auto              = validate

# Dialecto especifico de MySQL 8
#spring.jpa.database-platform               = org.hibernate.dialect.MySQL8Dialect
# Muestra SQL en consola (util en desarrollo)
#spring.jpa.show-sql                        = true
# Da formato al SQL mostrado
#spring.jpa.properties.hibernate.format_sql = true


#spring.autoconfigure.exclude               = org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# ===============================
# Configuracion de Aiven MySQL
# ===============================
# Cambiamos localhost por el hostname de Aiven y el puerto
spring.datasource.url=jdbc:mysql://vet-manada-woof-idaticre.a.aivencloud.com:28299/vet_manada_woof?ssl-mode=REQUIRED

spring.datasource.username                              = avnadmin
spring.datasource.password                              = AVNS_fzbUv-SBSHxPcdLyj1l
spring.datasource.driver-class-name                     = com.mysql.cj.jdbc.Driver

# SSL requerido por Aiven
spring.datasource.hikari.data-source-properties.sslMode = REQUIRED

# ===============================
# JPA / Hibernate
# ===============================
# IMPORTANTE: Cambia 'validate' a 'update' la primera vez para que
# Hibernate cree las tablas en Aiven automaticamente.
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform                            = org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql                                     = true

spring.jpa.hibernate.ddl-auto                           = validate
